// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package wls

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

/// Represents an action taken post evaluation
type Action struct {
	_tab flatbuffers.Table
}

func GetRootAsAction(buf []byte, offset flatbuffers.UOffsetT) *Action {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &Action{}
	x.Init(buf, n+offset)
	return x
}

func FinishActionBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsAction(buf []byte, offset flatbuffers.UOffsetT) *Action {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &Action{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedActionBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *Action) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *Action) Table() flatbuffers.Table {
	return rcv._tab
}

/// An enum representing the type of action to take.
func (rcv *Action) Action() ActionId {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return ActionId(rcv._tab.GetInt8(o + rcv._tab.Pos))
	}
	return 0
}

/// An enum representing the type of action to take.
func (rcv *Action) MutateAction(n ActionId) bool {
	return rcv._tab.MutateInt8Slot(4, int8(n))
}

/// For debugging purposes a description string can be passed 
func (rcv *Action) Description() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

/// For debugging purposes a description string can be passed 
/// Each action defines the values it accepts\supports.
func (rcv *Action) Values(j int) []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		a := rcv._tab.Vector(o)
		return rcv._tab.ByteVector(a + flatbuffers.UOffsetT(j*4))
	}
	return nil
}

func (rcv *Action) ValuesLength() int {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		return rcv._tab.VectorLen(o)
	}
	return 0
}

/// Each action defines the values it accepts\supports.
func ActionStart(builder *flatbuffers.Builder) {
	builder.StartObject(3)
}
func ActionAddAction(builder *flatbuffers.Builder, action ActionId) {
	builder.PrependInt8Slot(0, int8(action), 0)
}
func ActionAddDescription(builder *flatbuffers.Builder, description flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(1, flatbuffers.UOffsetT(description), 0)
}
func ActionAddValues(builder *flatbuffers.Builder, values flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(2, flatbuffers.UOffsetT(values), 0)
}
func ActionStartValuesVector(builder *flatbuffers.Builder, numElems int) flatbuffers.UOffsetT {
	return builder.StartVector(4, numElems, 4)
}
func ActionEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
