// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package wls

import "strconv"

/// Each Action should have an ID associated with it - it should be unique! 
/// IMPORTANT! When adding a new action make sure you add it as the last one (just before the ACTIONS_COUNT entry)
type ActionId int8

const (
	/// \brief used a fallback and default incase of a failed parsing
	ActionIdACTION_UNKNOWN  ActionId = 0
	ActionIdINJECT_DENY     ActionId = 1
	ActionIdINJECT_ALLOW    ActionId = 2
	ActionIdENABLE_SDK      ActionId = 3
	ActionIdENABLE_PROFILER ActionId = 4
	ActionIdSET_ENVAR       ActionId = 5
	/// string values should be: <prefix> <postfix>
	/// for example to turn "someapp arg1 arg2" into "wrapper_bin wrapper_arg wrapper_arg2 someapp arg1 arg2 --anotherarg=1 --anotherarg2 anotherval"
	/// you should pass {"wrapper_bin wrapper_arg wrapper_arg2", "--anotherarg=1 --anotherarg2 anotherval"}
	/// its on the action implementation to seperate these into execve arguments
	ActionIdREEXEC          ActionId = 6
	ActionIdACTIONS_COUNT   ActionId = 7
)

var EnumNamesActionId = map[ActionId]string{
	ActionIdACTION_UNKNOWN:  "ACTION_UNKNOWN",
	ActionIdINJECT_DENY:     "INJECT_DENY",
	ActionIdINJECT_ALLOW:    "INJECT_ALLOW",
	ActionIdENABLE_SDK:      "ENABLE_SDK",
	ActionIdENABLE_PROFILER: "ENABLE_PROFILER",
	ActionIdSET_ENVAR:       "SET_ENVAR",
	ActionIdREEXEC:          "REEXEC",
	ActionIdACTIONS_COUNT:   "ACTIONS_COUNT",
}

var EnumValuesActionId = map[string]ActionId{
	"ACTION_UNKNOWN":  ActionIdACTION_UNKNOWN,
	"INJECT_DENY":     ActionIdINJECT_DENY,
	"INJECT_ALLOW":    ActionIdINJECT_ALLOW,
	"ENABLE_SDK":      ActionIdENABLE_SDK,
	"ENABLE_PROFILER": ActionIdENABLE_PROFILER,
	"SET_ENVAR":       ActionIdSET_ENVAR,
	"REEXEC":          ActionIdREEXEC,
	"ACTIONS_COUNT":   ActionIdACTIONS_COUNT,
}

func (v ActionId) String() string {
	if s, ok := EnumNamesActionId[v]; ok {
		return s
	}
	return "ActionId(" + strconv.FormatInt(int64(v), 10) + ")"
}
