// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package wls

import "strconv"

// / Max values that can be propogated across languages.
type ActionMax int16

const (
	/// The maximum number of values an action can have.
	/// This is used to ensure that the action values do not exceed this limit.
	ActionMaxACTION_VALUES_MAX ActionMax = 255
)

var EnumNamesActionMax = map[ActionMax]string{
	ActionMaxACTION_VALUES_MAX: "ACTION_VALUES_MAX",
}

var EnumValuesActionMax = map[string]ActionMax{
	"ACTION_VALUES_MAX": ActionMaxACTION_VALUES_MAX,
}

func (v ActionMax) String() string {
	if s, ok := EnumNamesActionMax[v]; ok {
		return s
	}
	return "ActionMax(" + strconv.FormatInt(int64(v), 10) + ")"
}
