// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package wls

import "strconv"

// / These are the supported boolean operators when evaluating multiple conditions
type BoolOperation int8

const (
	/// \brief used a fallback and default incase of a failed parsing
	BoolOperationBOOL_UNKNOWN BoolOperation = 0
	BoolOperationBOOL_AND     BoolOperation = 1
	BoolOperationBOOL_NOT     BoolOperation = 2
	BoolOperationBOOL_OR      BoolOperation = 3
	BoolOperationBOOL_COUNT   BoolOperation = 4
)

var EnumNamesBoolOperation = map[BoolOperation]string{
	BoolOperationBOOL_UNKNOWN: "BOOL_UNKNOWN",
	BoolOperationBOOL_AND:     "BOOL_AND",
	BoolOperationBOOL_NOT:     "BOOL_NOT",
	BoolOperationBOOL_OR:      "BOOL_OR",
	BoolOperationBOOL_COUNT:   "BOOL_COUNT",
}

var EnumValuesBoolOperation = map[string]BoolOperation{
	"BOOL_UNKNOWN": BoolOperationBOOL_UNKNOWN,
	"BOOL_AND":     BoolOperationBOOL_AND,
	"BOOL_NOT":     BoolOperationBOOL_NOT,
	"BOOL_OR":      BoolOperationBOOL_OR,
	"BOOL_COUNT":   BoolOperationBOOL_COUNT,
}

func (v BoolOperation) String() string {
	if s, ok := EnumNamesBoolOperation[v]; ok {
		return s
	}
	return "BoolOperation(" + strconv.FormatInt(int64(v), 10) + ")"
}
