// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package wls

import "strconv"

/// These are the supported comparison operators for Numeric evaluators:
/// CMP_EQ : Compare equal `==`
/// CMP_GT : Compare Greater Than `>`
/// CMP_GTE : Compare Greater Than Equal `>=`
/// CMP_LT : Compare Lower Than `<`
/// CMP_LTE : Compare Lower Than Equal `<=`
type CmpTypeNUM int8

const (
	/// An enum representing the type of action to take.
	CmpTypeNUMCMP_NUM_UNKNOWN CmpTypeNUM = 0
	CmpTypeNUMCMP_EQ          CmpTypeNUM = 1
	CmpTypeNUMCMP_GT          CmpTypeNUM = 2
	CmpTypeNUMCMP_GTE         CmpTypeNUM = 3
	CmpTypeNUMCMP_LT          CmpTypeNUM = 4
	CmpTypeNUMCMP_LTE         CmpTypeNUM = 5
	CmpTypeNUMCMP_COUNT       CmpTypeNUM = 6
)

var EnumNamesCmpTypeNUM = map[CmpTypeNUM]string{
	CmpTypeNUMCMP_NUM_UNKNOWN: "CMP_NUM_UNKNOWN",
	CmpTypeNUMCMP_EQ:          "CMP_EQ",
	CmpTypeNUMCMP_GT:          "CMP_GT",
	CmpTypeNUMCMP_GTE:         "CMP_GTE",
	CmpTypeNUMCMP_LT:          "CMP_LT",
	CmpTypeNUMCMP_LTE:         "CMP_LTE",
	CmpTypeNUMCMP_COUNT:       "CMP_COUNT",
}

var EnumValuesCmpTypeNUM = map[string]CmpTypeNUM{
	"CMP_NUM_UNKNOWN": CmpTypeNUMCMP_NUM_UNKNOWN,
	"CMP_EQ":          CmpTypeNUMCMP_EQ,
	"CMP_GT":          CmpTypeNUMCMP_GT,
	"CMP_GTE":         CmpTypeNUMCMP_GTE,
	"CMP_LT":          CmpTypeNUMCMP_LT,
	"CMP_LTE":         CmpTypeNUMCMP_LTE,
	"CMP_COUNT":       CmpTypeNUMCMP_COUNT,
}

func (v CmpTypeNUM) String() string {
	if s, ok := EnumNamesCmpTypeNUM[v]; ok {
		return s
	}
	return "CmpTypeNUM(" + strconv.FormatInt(int64(v), 10) + ")"
}
