// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package wls

import "strconv"

/// These are the supported comparison operators for String evaluators:
/// CMP_PREFIX : Compare if the string starts with the value
/// CMP_SUFFIX : Compare if the string ends with the value
/// CMP_CONTAINS : Compare if the string contains the value
/// CMP_EXACT : Compare if the string is exactly equal to the value
/// CMP_WILDCARD : Compare using wildcard matching ('?' single char, '*' any chars)
type CmpTypeSTR int8

const (
	/// An enum representing the type of action to take.
	CmpTypeSTRCMP_STR_UNKNOWN CmpTypeSTR = 0
	CmpTypeSTRCMP_PREFIX      CmpTypeSTR = 1
	CmpTypeSTRCMP_SUFFIX      CmpTypeSTR = 2
	CmpTypeSTRCMP_CONTAINS    CmpTypeSTR = 3
	CmpTypeSTRCMP_EXACT       CmpTypeSTR = 4
	CmpTypeSTRCMP_WILDCARD    CmpTypeSTR = 5
	CmpTypeSTRCMP_COUNT       CmpTypeSTR = 6
)

var EnumNamesCmpTypeSTR = map[CmpTypeSTR]string{
	CmpTypeSTRCMP_STR_UNKNOWN: "CMP_STR_UNKNOWN",
	CmpTypeSTRCMP_PREFIX:      "CMP_PREFIX",
	CmpTypeSTRCMP_SUFFIX:      "CMP_SUFFIX",
	CmpTypeSTRCMP_CONTAINS:    "CMP_CONTAINS",
	CmpTypeSTRCMP_EXACT:       "CMP_EXACT",
	CmpTypeSTRCMP_WILDCARD:    "CMP_WILDCARD",
	CmpTypeSTRCMP_COUNT:       "CMP_COUNT",
}

var EnumValuesCmpTypeSTR = map[string]CmpTypeSTR{
	"CMP_STR_UNKNOWN": CmpTypeSTRCMP_STR_UNKNOWN,
	"CMP_PREFIX":      CmpTypeSTRCMP_PREFIX,
	"CMP_SUFFIX":      CmpTypeSTRCMP_SUFFIX,
	"CMP_CONTAINS":    CmpTypeSTRCMP_CONTAINS,
	"CMP_EXACT":       CmpTypeSTRCMP_EXACT,
	"CMP_WILDCARD":    CmpTypeSTRCMP_WILDCARD,
	"CMP_COUNT":       CmpTypeSTRCMP_COUNT,
}

func (v CmpTypeSTR) String() string {
	if s, ok := EnumNamesCmpTypeSTR[v]; ok {
		return s
	}
	return "CmpTypeSTR(" + strconv.FormatInt(int64(v), 10) + ")"
}
