// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package wls

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

/// Represents a root node in the policy tree.
/// It contains a description, a boolean operation (AND, OR, NOT) and a list of child nodes.
/// The children are wrapped in NodeTypeWrapper to allow for union vectors.
type CompositeNode struct {
	_tab flatbuffers.Table
}

func GetRootAsCompositeNode(buf []byte, offset flatbuffers.UOffsetT) *CompositeNode {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &CompositeNode{}
	x.Init(buf, n+offset)
	return x
}

func FinishCompositeNodeBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsCompositeNode(buf []byte, offset flatbuffers.UOffsetT) *CompositeNode {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &CompositeNode{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedCompositeNodeBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *CompositeNode) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *CompositeNode) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *CompositeNode) Description() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *CompositeNode) Op() BoolOperation {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return BoolOperation(rcv._tab.GetInt8(o + rcv._tab.Pos))
	}
	return 0
}

func (rcv *CompositeNode) MutateOp(n BoolOperation) bool {
	return rcv._tab.MutateInt8Slot(6, int8(n))
}

/// At some point we will switch back to; children: [NodeType]; 
/// (union vectors are not supported in GO so we are wrapping the table in a table)
func (rcv *CompositeNode) Children(obj *NodeTypeWrapper, j int) bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		x := rcv._tab.Vector(o)
		x += flatbuffers.UOffsetT(j) * 4
		x = rcv._tab.Indirect(x)
		obj.Init(rcv._tab.Bytes, x)
		return true
	}
	return false
}

func (rcv *CompositeNode) ChildrenLength() int {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		return rcv._tab.VectorLen(o)
	}
	return 0
}

/// At some point we will switch back to; children: [NodeType]; 
/// (union vectors are not supported in GO so we are wrapping the table in a table)
func CompositeNodeStart(builder *flatbuffers.Builder) {
	builder.StartObject(3)
}
func CompositeNodeAddDescription(builder *flatbuffers.Builder, description flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(description), 0)
}
func CompositeNodeAddOp(builder *flatbuffers.Builder, op BoolOperation) {
	builder.PrependInt8Slot(1, int8(op), 0)
}
func CompositeNodeAddChildren(builder *flatbuffers.Builder, children flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(2, flatbuffers.UOffsetT(children), 0)
}
func CompositeNodeStartChildrenVector(builder *flatbuffers.Builder, numElems int) flatbuffers.UOffsetT {
	return builder.StartVector(4, numElems, 4)
}
func CompositeNodeEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
