// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package wls

import "strconv"

// / Represents an 'optional' Boolean results where EVAL_RESULT_ABSTAIN is a *dont care* result.
// / For more details about the *dont care* results please refer the RFC\Documentation.
type EvaluationResult int8

const (
	EvaluationResultEVAL_RESULT_ABSTAIN EvaluationResult = -1
	EvaluationResultEVAL_RESULT_FALSE   EvaluationResult = 0
	EvaluationResultEVAL_RESULT_TRUE    EvaluationResult = 1
	/// Synthetic count to align with other enumerations
	EvaluationResultEVAL_RESULT_COUNT EvaluationResult = 3
)

var EnumNamesEvaluationResult = map[EvaluationResult]string{
	EvaluationResultEVAL_RESULT_ABSTAIN: "EVAL_RESULT_ABSTAIN",
	EvaluationResultEVAL_RESULT_FALSE:   "EVAL_RESULT_FALSE",
	EvaluationResultEVAL_RESULT_TRUE:    "EVAL_RESULT_TRUE",
	EvaluationResultEVAL_RESULT_COUNT:   "EVAL_RESULT_COUNT",
}

var EnumValuesEvaluationResult = map[string]EvaluationResult{
	"EVAL_RESULT_ABSTAIN": EvaluationResultEVAL_RESULT_ABSTAIN,
	"EVAL_RESULT_FALSE":   EvaluationResultEVAL_RESULT_FALSE,
	"EVAL_RESULT_TRUE":    EvaluationResultEVAL_RESULT_TRUE,
	"EVAL_RESULT_COUNT":   EvaluationResultEVAL_RESULT_COUNT,
}

func (v EvaluationResult) String() string {
	if s, ok := EnumNamesEvaluationResult[v]; ok {
		return s
	}
	return "EvaluationResult(" + strconv.FormatInt(int64(v), 10) + ")"
}
