// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package wls

import "strconv"

/// EvaluatorType is a union of all the evaluators supported by the policy engine.
/// NOTE: StrArrEvaluator is not supported yet, but it is reserved for future use.
type EvaluatorType byte

const (
	EvaluatorTypeNONE          EvaluatorType = 0
	EvaluatorTypeStrEvaluator  EvaluatorType = 1
	EvaluatorTypeNumEvaluator  EvaluatorType = 2
	EvaluatorTypeUNumEvaluator EvaluatorType = 3
)

var EnumNamesEvaluatorType = map[EvaluatorType]string{
	EvaluatorTypeNONE:          "NONE",
	EvaluatorTypeStrEvaluator:  "StrEvaluator",
	EvaluatorTypeNumEvaluator:  "NumEvaluator",
	EvaluatorTypeUNumEvaluator: "UNumEvaluator",
}

var EnumValuesEvaluatorType = map[string]EvaluatorType{
	"NONE":          EvaluatorTypeNONE,
	"StrEvaluator":  EvaluatorTypeStrEvaluator,
	"NumEvaluator":  EvaluatorTypeNumEvaluator,
	"UNumEvaluator": EvaluatorTypeUNumEvaluator,
}

func (v EvaluatorType) String() string {
	if s, ok := EnumNamesEvaluatorType[v]; ok {
		return s
	}
	return "EvaluatorType(" + strconv.FormatInt(int64(v), 10) + ")"
}
