// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package wls

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

/// Represents a leaf node in the policy tree.
/// It contains a description and an evaluator.
type EvaluatorNode struct {
	_tab flatbuffers.Table
}

func GetRootAsEvaluatorNode(buf []byte, offset flatbuffers.UOffsetT) *EvaluatorNode {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &EvaluatorNode{}
	x.Init(buf, n+offset)
	return x
}

func FinishEvaluatorNodeBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsEvaluatorNode(buf []byte, offset flatbuffers.UOffsetT) *EvaluatorNode {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &EvaluatorNode{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedEvaluatorNodeBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *EvaluatorNode) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *EvaluatorNode) Table() flatbuffers.Table {
	return rcv._tab
}

/// The description is used for debugging purposes.
func (rcv *EvaluatorNode) Description() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

/// The description is used for debugging purposes.
func (rcv *EvaluatorNode) EvalType() EvaluatorType {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return EvaluatorType(rcv._tab.GetByte(o + rcv._tab.Pos))
	}
	return 0
}

func (rcv *EvaluatorNode) MutateEvalType(n EvaluatorType) bool {
	return rcv._tab.MutateByteSlot(6, byte(n))
}

/// The evaluator is a union of different evaluator types (String, Numeric, etc.).
func (rcv *EvaluatorNode) Eval(obj *flatbuffers.Table) bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		rcv._tab.Union(obj, o)
		return true
	}
	return false
}

/// The evaluator is a union of different evaluator types (String, Numeric, etc.).
func EvaluatorNodeStart(builder *flatbuffers.Builder) {
	builder.StartObject(3)
}
func EvaluatorNodeAddDescription(builder *flatbuffers.Builder, description flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(description), 0)
}
func EvaluatorNodeAddEvalType(builder *flatbuffers.Builder, evalType EvaluatorType) {
	builder.PrependByteSlot(1, byte(evalType), 0)
}
func EvaluatorNodeAddEval(builder *flatbuffers.Builder, eval flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(2, flatbuffers.UOffsetT(eval), 0)
}
func EvaluatorNodeEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
