// Code generated by the FlatBuffers to JSON generator. DO NOT EDIT.
package wls

import (
	"encoding/json"
	"fmt"
)

type ActionJSON struct {
	Action      ActionId `json:"action"`
	Description string   `json:"description"`
	Values      []string `json:"values"`
}

type StrEvaluatorJSON struct {
	Id    StringEvaluators `json:"id"`
	Cmp   CmpTypeSTR       `json:"cmp"`
	Value string           `json:"value"`
}

type UNumEvaluatorJSON struct {
	Id    NumericEvaluators `json:"id"`
	Cmp   CmpTypeNUM        `json:"cmp"`
	Value uint64            `json:"value"`
}

type NumEvaluatorJSON struct {
	Id    NumericEvaluators `json:"id"`
	Cmp   CmpTypeNUM        `json:"cmp"`
	Value int64             `json:"value"`
}

type NodeTypeWrapperJSON struct {
	NodeType NodeType        `json:"node_type"`
	Node     json.RawMessage `json:"node"`
}

func (o *NodeTypeWrapperJSON) DecodeNode() (interface{}, error) {
	switch o.NodeType {
	case NodeTypeEvaluatorNode:
		var v EvaluatorNodeJSON
		if err := json.Unmarshal(o.Node, &v); err != nil {
			return nil, err
		}
		return v, nil
	case NodeTypeCompositeNode:
		var v CompositeNodeJSON
		if err := json.Unmarshal(o.Node, &v); err != nil {
			return nil, err
		}
		return v, nil
	case NodeTypeNONE:
		return struct{}{}, nil
	default:
		return nil, fmt.Errorf("unknown NodeType: %s", o.NodeType)
	}
}

type CompositeNodeJSON struct {
	Description string                `json:"description"`
	Op          BoolOperation         `json:"op"`
	Children    []NodeTypeWrapperJSON `json:"children"`
}

type EvaluatorNodeJSON struct {
	Description string          `json:"description"`
	EvalType    EvaluatorType   `json:"eval_type"`
	Eval        json.RawMessage `json:"eval"`
}

func (o *EvaluatorNodeJSON) DecodeEval() (interface{}, error) {
	switch o.EvalType {
	case EvaluatorTypeStrEvaluator:
		var v StrEvaluatorJSON
		if err := json.Unmarshal(o.Eval, &v); err != nil {
			return nil, err
		}
		return v, nil
	case EvaluatorTypeNumEvaluator:
		var v NumEvaluatorJSON
		if err := json.Unmarshal(o.Eval, &v); err != nil {
			return nil, err
		}
		return v, nil
	case EvaluatorTypeUNumEvaluator:
		var v UNumEvaluatorJSON
		if err := json.Unmarshal(o.Eval, &v); err != nil {
			return nil, err
		}
		return v, nil
	case EvaluatorTypeNONE:
		return struct{}{}, nil
	default:
		return nil, fmt.Errorf("unknown EvalType: %s", o.EvalType)
	}
}

type PolicyJSON struct {
	Description string              `json:"description"`
	Rules       NodeTypeWrapperJSON `json:"rules"`
	Actions     []ActionJSON        `json:"actions"`
}

type PoliciesJSON struct {
	Policies []PolicyJSON `json:"policies"`
}

func (e *EvaluatorType) UnmarshalJSON(data []byte) error {
	var s string
	if err := json.Unmarshal(data, &s); err != nil {
		return err
	}
	if val, ok := EnumValuesEvaluatorType[s]; ok {
		*e = EvaluatorType(val)
		return nil
	}
	*e = EvaluatorTypeNONE
	return nil
}

func (e *NodeType) UnmarshalJSON(data []byte) error {
	var s string
	if err := json.Unmarshal(data, &s); err != nil {
		return err
	}
	if val, ok := EnumValuesNodeType[s]; ok {
		*e = NodeType(val)
		return nil
	}
	*e = NodeTypeNONE
	return nil
}

func (e *ActionId) UnmarshalJSON(data []byte) error {
	var s string
	if err := json.Unmarshal(data, &s); err != nil {
		return err
	}
	if val, ok := EnumValuesActionId[s]; ok {
		*e = ActionId(val)
		return nil
	}
	*e = ActionIdINJECT_DENY // TODO: have a distinct default
	return nil
}

func (e *ActionMax) UnmarshalJSON(data []byte) error {
	var s string
	if err := json.Unmarshal(data, &s); err != nil {
		return err
	}
	if val, ok := EnumValuesActionMax[s]; ok {
		*e = ActionMax(val)
		return nil
	}
	*e = ActionMaxACTION_VALUES_MAX // TODO: have a distinct default
	return nil
}

func (e *BoolOperation) UnmarshalJSON(data []byte) error {
	var s string
	if err := json.Unmarshal(data, &s); err != nil {
		return err
	}
	if val, ok := EnumValuesBoolOperation[s]; ok {
		*e = BoolOperation(val)
		return nil
	}
	*e = BoolOperationBOOL_AND // TODO: have a distinct default
	return nil
}

func (e *EvaluationResult) UnmarshalJSON(data []byte) error {
	var s string
	if err := json.Unmarshal(data, &s); err != nil {
		return err
	}
	if val, ok := EnumValuesEvaluationResult[s]; ok {
		*e = EvaluationResult(val)
		return nil
	}
	*e = EvaluationResultEVAL_RESULT_ABSTAIN
	return nil
}

func (e *StringEvaluators) UnmarshalJSON(data []byte) error {
	var s string
	if err := json.Unmarshal(data, &s); err != nil {
		return err
	}
	if val, ok := EnumValuesStringEvaluators[s]; ok {
		*e = StringEvaluators(val)
		return nil
	}
	*e = StringEvaluatorsCOMPONENT // TODO: have a distinct default
	return nil
}

func (e *NumericEvaluators) UnmarshalJSON(data []byte) error {
	var s string
	if err := json.Unmarshal(data, &s); err != nil {
		return err
	}
	if val, ok := EnumValuesNumericEvaluators[s]; ok {
		*e = NumericEvaluators(val)
		return nil
	}
	*e = NumericEvaluatorsJAVA_HEAP // TODO: have a distinct default
	return nil
}

func (e *CmpTypeNUM) UnmarshalJSON(data []byte) error {
	var s string
	if err := json.Unmarshal(data, &s); err != nil {
		return err
	}
	if val, ok := EnumValuesCmpTypeNUM[s]; ok {
		*e = CmpTypeNUM(val)
		return nil
	}
	*e = CmpTypeNUMCMP_EQ // TODO: have a distinct default
	return nil
}

func (e *CmpTypeSTR) UnmarshalJSON(data []byte) error {
	var s string
	if err := json.Unmarshal(data, &s); err != nil {
		return err
	}
	if val, ok := EnumValuesCmpTypeSTR[s]; ok {
		*e = CmpTypeSTR(val)
		return nil
	}
	*e = CmpTypeSTRCMP_PREFIX // TODO: have a distinct default
	return nil
}
