// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package wls

import "strconv"

/// Represents the type of node in the policy tree.
/// It can either be a leaf node (which contains an evaluator) or a root node (which contains children nodes).
/// The NodeType is a union of EvaluatorNode and CompositeNode.
type NodeType byte

const (
	NodeTypeNONE          NodeType = 0
	NodeTypeEvaluatorNode NodeType = 1
	NodeTypeCompositeNode NodeType = 2
)

var EnumNamesNodeType = map[NodeType]string{
	NodeTypeNONE:          "NONE",
	NodeTypeEvaluatorNode: "EvaluatorNode",
	NodeTypeCompositeNode: "CompositeNode",
}

var EnumValuesNodeType = map[string]NodeType{
	"NONE":          NodeTypeNONE,
	"EvaluatorNode": NodeTypeEvaluatorNode,
	"CompositeNode": NodeTypeCompositeNode,
}

func (v NodeType) String() string {
	if s, ok := EnumNamesNodeType[v]; ok {
		return s
	}
	return "NodeType(" + strconv.FormatInt(int64(v), 10) + ")"
}
