// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package wls

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

/// Represents a wrapper for NodeType to allow for union vectors in FlatBuffers.
/// This is necessary because union vectors are not supported directly in all FlatBuffers implementations :(
type NodeTypeWrapper struct {
	_tab flatbuffers.Table
}

func GetRootAsNodeTypeWrapper(buf []byte, offset flatbuffers.UOffsetT) *NodeTypeWrapper {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &NodeTypeWrapper{}
	x.Init(buf, n+offset)
	return x
}

func FinishNodeTypeWrapperBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsNodeTypeWrapper(buf []byte, offset flatbuffers.UOffsetT) *NodeTypeWrapper {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &NodeTypeWrapper{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedNodeTypeWrapperBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *NodeTypeWrapper) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *NodeTypeWrapper) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *NodeTypeWrapper) NodeType() NodeType {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return NodeType(rcv._tab.GetByte(o + rcv._tab.Pos))
	}
	return 0
}

func (rcv *NodeTypeWrapper) MutateNodeType(n NodeType) bool {
	return rcv._tab.MutateByteSlot(4, byte(n))
}

func (rcv *NodeTypeWrapper) Node(obj *flatbuffers.Table) bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		rcv._tab.Union(obj, o)
		return true
	}
	return false
}

func NodeTypeWrapperStart(builder *flatbuffers.Builder) {
	builder.StartObject(2)
}
func NodeTypeWrapperAddNodeType(builder *flatbuffers.Builder, nodeType NodeType) {
	builder.PrependByteSlot(0, byte(nodeType), 0)
}
func NodeTypeWrapperAddNode(builder *flatbuffers.Builder, node flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(1, flatbuffers.UOffsetT(node), 0)
}
func NodeTypeWrapperEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
