// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package wls

import "strconv"

// / Each ID represents a Numeric evaluator
// / Each evaluator ID should be UNIQUE!
// / The numeric evaluators are the same for signed and unsigned types.
// / IMPORTANT! When adding a new evaluator make sure you add it as the last one (just before the _COUNT entry)
type NumericEvaluators int8

const (
	/// An enum representing the type of action to take.
	NumericEvaluatorsNUMERIC_EVAL_UNKNOWN    NumericEvaluators = 0
	NumericEvaluatorsJAVA_HEAP               NumericEvaluators = 1
	NumericEvaluatorsRUNTIME_VERSION_MAJOR   NumericEvaluators = 2
	NumericEvaluatorsRUNTIME_VERSION_MINOR   NumericEvaluators = 3
	NumericEvaluatorsRUNTIME_VERSION_PATCH   NumericEvaluators = 4
	NumericEvaluatorsOS_DISTRO_VERSION_MAJOR NumericEvaluators = 5
	NumericEvaluatorsOS_DISTRO_VERSION_MINOR NumericEvaluators = 6
	NumericEvaluatorsOS_DISTRO_VERSION_PATCH NumericEvaluators = 7
	NumericEvaluatorsOS_KERNEL_VERSION_MAJOR NumericEvaluators = 8
	NumericEvaluatorsOS_KERNEL_VERSION_MINOR NumericEvaluators = 9
	NumericEvaluatorsOS_KERNEL_VERSION_PATCH NumericEvaluators = 10
	NumericEvaluatorsLIBC_VERSION_MAJOR      NumericEvaluators = 11
	NumericEvaluatorsLIBC_VERSION_MINOR      NumericEvaluators = 12
	NumericEvaluatorsLIBC_VERSION_PATCH      NumericEvaluators = 13
	/// Represents the count of Numeric evaluators.
	/// This is used to ensure that the enum is always in sync with the number of evaluators.
	/// IMPORTANT! When adding a new evaluator make sure you add it BEFORE this entry.
	NumericEvaluatorsNUM_EVAL_COUNT NumericEvaluators = 14
)

var EnumNamesNumericEvaluators = map[NumericEvaluators]string{
	NumericEvaluatorsNUMERIC_EVAL_UNKNOWN:    "NUMERIC_EVAL_UNKNOWN",
	NumericEvaluatorsJAVA_HEAP:               "JAVA_HEAP",
	NumericEvaluatorsRUNTIME_VERSION_MAJOR:   "RUNTIME_VERSION_MAJOR",
	NumericEvaluatorsRUNTIME_VERSION_MINOR:   "RUNTIME_VERSION_MINOR",
	NumericEvaluatorsRUNTIME_VERSION_PATCH:   "RUNTIME_VERSION_PATCH",
	NumericEvaluatorsOS_DISTRO_VERSION_MAJOR: "OS_DISTRO_VERSION_MAJOR",
	NumericEvaluatorsOS_DISTRO_VERSION_MINOR: "OS_DISTRO_VERSION_MINOR",
	NumericEvaluatorsOS_DISTRO_VERSION_PATCH: "OS_DISTRO_VERSION_PATCH",
	NumericEvaluatorsOS_KERNEL_VERSION_MAJOR: "OS_KERNEL_VERSION_MAJOR",
	NumericEvaluatorsOS_KERNEL_VERSION_MINOR: "OS_KERNEL_VERSION_MINOR",
	NumericEvaluatorsOS_KERNEL_VERSION_PATCH: "OS_KERNEL_VERSION_PATCH",
	NumericEvaluatorsLIBC_VERSION_MAJOR:      "LIBC_VERSION_MAJOR",
	NumericEvaluatorsLIBC_VERSION_MINOR:      "LIBC_VERSION_MINOR",
	NumericEvaluatorsLIBC_VERSION_PATCH:      "LIBC_VERSION_PATCH",
	NumericEvaluatorsNUM_EVAL_COUNT:          "NUM_EVAL_COUNT",
}

var EnumValuesNumericEvaluators = map[string]NumericEvaluators{
	"NUMERIC_EVAL_UNKNOWN":    NumericEvaluatorsNUMERIC_EVAL_UNKNOWN,
	"JAVA_HEAP":               NumericEvaluatorsJAVA_HEAP,
	"RUNTIME_VERSION_MAJOR":   NumericEvaluatorsRUNTIME_VERSION_MAJOR,
	"RUNTIME_VERSION_MINOR":   NumericEvaluatorsRUNTIME_VERSION_MINOR,
	"RUNTIME_VERSION_PATCH":   NumericEvaluatorsRUNTIME_VERSION_PATCH,
	"OS_DISTRO_VERSION_MAJOR": NumericEvaluatorsOS_DISTRO_VERSION_MAJOR,
	"OS_DISTRO_VERSION_MINOR": NumericEvaluatorsOS_DISTRO_VERSION_MINOR,
	"OS_DISTRO_VERSION_PATCH": NumericEvaluatorsOS_DISTRO_VERSION_PATCH,
	"OS_KERNEL_VERSION_MAJOR": NumericEvaluatorsOS_KERNEL_VERSION_MAJOR,
	"OS_KERNEL_VERSION_MINOR": NumericEvaluatorsOS_KERNEL_VERSION_MINOR,
	"OS_KERNEL_VERSION_PATCH": NumericEvaluatorsOS_KERNEL_VERSION_PATCH,
	"LIBC_VERSION_MAJOR":      NumericEvaluatorsLIBC_VERSION_MAJOR,
	"LIBC_VERSION_MINOR":      NumericEvaluatorsLIBC_VERSION_MINOR,
	"LIBC_VERSION_PATCH":      NumericEvaluatorsLIBC_VERSION_PATCH,
	"NUM_EVAL_COUNT":          NumericEvaluatorsNUM_EVAL_COUNT,
}

func (v NumericEvaluators) String() string {
	if s, ok := EnumNamesNumericEvaluators[v]; ok {
		return s
	}
	return "NumericEvaluators(" + strconv.FormatInt(int64(v), 10) + ")"
}
