// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package wls

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

/// Represents a signed Numeric evaluator
/// This evaluator is used for signed numeric comparisons.
type NumEvaluator struct {
	_tab flatbuffers.Table
}

func GetRootAsNumEvaluator(buf []byte, offset flatbuffers.UOffsetT) *NumEvaluator {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &NumEvaluator{}
	x.Init(buf, n+offset)
	return x
}

func FinishNumEvaluatorBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsNumEvaluator(buf []byte, offset flatbuffers.UOffsetT) *NumEvaluator {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &NumEvaluator{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedNumEvaluatorBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *NumEvaluator) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *NumEvaluator) Table() flatbuffers.Table {
	return rcv._tab
}

/// Each evaluator has an ID, a comparison type and a value to compare against.
func (rcv *NumEvaluator) Id() NumericEvaluators {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return NumericEvaluators(rcv._tab.GetInt8(o + rcv._tab.Pos))
	}
	return 0
}

/// Each evaluator has an ID, a comparison type and a value to compare against.
func (rcv *NumEvaluator) MutateId(n NumericEvaluators) bool {
	return rcv._tab.MutateInt8Slot(4, int8(n))
}

/// The comparison type is used to determine how to compare the value against the evaluator's value.
func (rcv *NumEvaluator) Cmp() CmpTypeNUM {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return CmpTypeNUM(rcv._tab.GetInt8(o + rcv._tab.Pos))
	}
	return 0
}

/// The comparison type is used to determine how to compare the value against the evaluator's value.
func (rcv *NumEvaluator) MutateCmp(n CmpTypeNUM) bool {
	return rcv._tab.MutateInt8Slot(6, int8(n))
}

/// The value is a signed long.
func (rcv *NumEvaluator) Value() int64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		return rcv._tab.GetInt64(o + rcv._tab.Pos)
	}
	return 0
}

/// The value is a signed long.
func (rcv *NumEvaluator) MutateValue(n int64) bool {
	return rcv._tab.MutateInt64Slot(8, n)
}

func NumEvaluatorStart(builder *flatbuffers.Builder) {
	builder.StartObject(3)
}
func NumEvaluatorAddId(builder *flatbuffers.Builder, id NumericEvaluators) {
	builder.PrependInt8Slot(0, int8(id), 0)
}
func NumEvaluatorAddCmp(builder *flatbuffers.Builder, cmp CmpTypeNUM) {
	builder.PrependInt8Slot(1, int8(cmp), 0)
}
func NumEvaluatorAddValue(builder *flatbuffers.Builder, value int64) {
	builder.PrependInt64Slot(2, value, 0)
}
func NumEvaluatorEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
