// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package wls

import "strconv"

// / Canonical set of operating systems recognized by the policy engine.
// / The string representation uses lowercase (e.g. "linux", "windows").
// / IMPORTANT! When adding a new value make sure you add it BEFORE the _COUNT entry.
type OperatingSystem int8

const (
	OperatingSystemOS_UNKNOWN OperatingSystem = 0
	OperatingSystemLINUX      OperatingSystem = 1
	OperatingSystemWINDOWS    OperatingSystem = 2
	OperatingSystemMACOS      OperatingSystem = 3
	OperatingSystemOS_COUNT   OperatingSystem = 4
)

var EnumNamesOperatingSystem = map[OperatingSystem]string{
	OperatingSystemOS_UNKNOWN: "OS_UNKNOWN",
	OperatingSystemLINUX:      "LINUX",
	OperatingSystemWINDOWS:    "WINDOWS",
	OperatingSystemMACOS:      "MACOS",
	OperatingSystemOS_COUNT:   "OS_COUNT",
}

var EnumValuesOperatingSystem = map[string]OperatingSystem{
	"OS_UNKNOWN": OperatingSystemOS_UNKNOWN,
	"LINUX":      OperatingSystemLINUX,
	"WINDOWS":    OperatingSystemWINDOWS,
	"MACOS":      OperatingSystemMACOS,
	"OS_COUNT":   OperatingSystemOS_COUNT,
}

func (v OperatingSystem) String() string {
	if s, ok := EnumNamesOperatingSystem[v]; ok {
		return s
	}
	return "OperatingSystem(" + strconv.FormatInt(int64(v), 10) + ")"
}
