// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package wls

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

/// Represents a collection of policies.
/// This allows for concatenation of policies from different sources.
/// The policies are stored in a vector of Policy.
/// This is also the root type of the FlatBuffer schema!!!
type Policies struct {
	_tab flatbuffers.Table
}

func GetRootAsPolicies(buf []byte, offset flatbuffers.UOffsetT) *Policies {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &Policies{}
	x.Init(buf, n+offset)
	return x
}

func FinishPoliciesBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsPolicies(buf []byte, offset flatbuffers.UOffsetT) *Policies {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &Policies{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedPoliciesBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *Policies) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *Policies) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *Policies) Policies(obj *Policy, j int) bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		x := rcv._tab.Vector(o)
		x += flatbuffers.UOffsetT(j) * 4
		x = rcv._tab.Indirect(x)
		obj.Init(rcv._tab.Bytes, x)
		return true
	}
	return false
}

func (rcv *Policies) PoliciesLength() int {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.VectorLen(o)
	}
	return 0
}

func PoliciesStart(builder *flatbuffers.Builder) {
	builder.StartObject(1)
}
func PoliciesAddPolicies(builder *flatbuffers.Builder, policies flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(policies), 0)
}
func PoliciesStartPoliciesVector(builder *flatbuffers.Builder, numElems int) flatbuffers.UOffsetT {
	return builder.StartVector(4, numElems, 4)
}
func PoliciesEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
