// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package wls

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

/// Represents a policy that contains rules and actions.
/// The rules are represented as a tree structure where each node can be a leaf (with an evaluator) or a root (with child nodes).
type Policy struct {
	_tab flatbuffers.Table
}

func GetRootAsPolicy(buf []byte, offset flatbuffers.UOffsetT) *Policy {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &Policy{}
	x.Init(buf, n+offset)
	return x
}

func FinishPolicyBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsPolicy(buf []byte, offset flatbuffers.UOffsetT) *Policy {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &Policy{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedPolicyBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *Policy) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *Policy) Table() flatbuffers.Table {
	return rcv._tab
}

/// The policy can have a description for debugging purposes.
func (rcv *Policy) Description() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

/// The policy can have a description for debugging purposes.
/// The rules are represented as a NodeTypeWrapper to allow for union vectors in FlatBuffers. 
func (rcv *Policy) Rules(obj *NodeTypeWrapper) *NodeTypeWrapper {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		x := rcv._tab.Indirect(o + rcv._tab.Pos)
		if obj == nil {
			obj = new(NodeTypeWrapper)
		}
		obj.Init(rcv._tab.Bytes, x)
		return obj
	}
	return nil
}

/// The rules are represented as a NodeTypeWrapper to allow for union vectors in FlatBuffers. 
/// The actions are taken post evaluation of the policy.
func (rcv *Policy) Actions(obj *Action, j int) bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		x := rcv._tab.Vector(o)
		x += flatbuffers.UOffsetT(j) * 4
		x = rcv._tab.Indirect(x)
		obj.Init(rcv._tab.Bytes, x)
		return true
	}
	return false
}

func (rcv *Policy) ActionsLength() int {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		return rcv._tab.VectorLen(o)
	}
	return 0
}

/// The actions are taken post evaluation of the policy.
/// 128 bit UUID represented as 16 raw bytes
/// this can be used to verify integrity (but NOT origin - this is not a signature!)
func (rcv *Policy) Id(obj *UUID) *UUID {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(10))
	if o != 0 {
		x := o + rcv._tab.Pos
		if obj == nil {
			obj = new(UUID)
		}
		obj.Init(rcv._tab.Bytes, x)
		return obj
	}
	return nil
}

/// 128 bit UUID represented as 16 raw bytes
/// this can be used to verify integrity (but NOT origin - this is not a signature!)
/// used to track the version number of this policy
func (rcv *Policy) Version() int64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(12))
	if o != 0 {
		return rcv._tab.GetInt64(o + rcv._tab.Pos)
	}
	return 0
}

/// used to track the version number of this policy
func (rcv *Policy) MutateVersion(n int64) bool {
	return rcv._tab.MutateInt64Slot(12, n)
}

/// Stable identifier of the rule this policy represents, used to attribute an
/// evaluation outcome back to its source rule (for example, linking a skipped
/// or instrumented process back to the rule on the Instrumentation Rules page).
/// For Remote Config rules this is the rule's UUID; for hardcoded/built-in
/// policies it is the sentinel "hardcoded".
func (rcv *Policy) RuleId() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(14))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func PolicyStart(builder *flatbuffers.Builder) {
	builder.StartObject(6)
}
func PolicyAddDescription(builder *flatbuffers.Builder, description flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(description), 0)
}
func PolicyAddRules(builder *flatbuffers.Builder, rules flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(1, flatbuffers.UOffsetT(rules), 0)
}
func PolicyAddActions(builder *flatbuffers.Builder, actions flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(2, flatbuffers.UOffsetT(actions), 0)
}
func PolicyStartActionsVector(builder *flatbuffers.Builder, numElems int) flatbuffers.UOffsetT {
	return builder.StartVector(4, numElems, 4)
}
func PolicyAddId(builder *flatbuffers.Builder, id flatbuffers.UOffsetT) {
	builder.PrependStructSlot(3, flatbuffers.UOffsetT(id), 0)
}
func PolicyAddVersion(builder *flatbuffers.Builder, version int64) {
	builder.PrependInt64Slot(4, version, 0)
}
func PolicyAddRuleId(builder *flatbuffers.Builder, ruleId flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(5, flatbuffers.UOffsetT(ruleId), 0)
}
func PolicyEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
