// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package wls

import "strconv"

// / Canonical set of runtime languages recognized by the policy engine.
// / The string representation uses lowercase (e.g. "jvm", "python").
// / IMPORTANT! When adding a new value make sure you add it BEFORE the _COUNT entry.
type RuntimeLanguage int8

const (
	RuntimeLanguageRUNTIME_LANGUAGE_UNKNOWN RuntimeLanguage = 0
	RuntimeLanguageJVM                      RuntimeLanguage = 1
	RuntimeLanguagePYTHON                   RuntimeLanguage = 2
	RuntimeLanguageRUBY                     RuntimeLanguage = 3
	RuntimeLanguageDOTNET                   RuntimeLanguage = 4
	RuntimeLanguageNODEJS                   RuntimeLanguage = 5
	RuntimeLanguagePHP                      RuntimeLanguage = 6
	RuntimeLanguageRUNTIME_LANGUAGE_COUNT   RuntimeLanguage = 7
)

var EnumNamesRuntimeLanguage = map[RuntimeLanguage]string{
	RuntimeLanguageRUNTIME_LANGUAGE_UNKNOWN: "RUNTIME_LANGUAGE_UNKNOWN",
	RuntimeLanguageJVM:                      "JVM",
	RuntimeLanguagePYTHON:                   "PYTHON",
	RuntimeLanguageRUBY:                     "RUBY",
	RuntimeLanguageDOTNET:                   "DOTNET",
	RuntimeLanguageNODEJS:                   "NODEJS",
	RuntimeLanguagePHP:                      "PHP",
	RuntimeLanguageRUNTIME_LANGUAGE_COUNT:   "RUNTIME_LANGUAGE_COUNT",
}

var EnumValuesRuntimeLanguage = map[string]RuntimeLanguage{
	"RUNTIME_LANGUAGE_UNKNOWN": RuntimeLanguageRUNTIME_LANGUAGE_UNKNOWN,
	"JVM":                      RuntimeLanguageJVM,
	"PYTHON":                   RuntimeLanguagePYTHON,
	"RUBY":                     RuntimeLanguageRUBY,
	"DOTNET":                   RuntimeLanguageDOTNET,
	"NODEJS":                   RuntimeLanguageNODEJS,
	"PHP":                      RuntimeLanguagePHP,
	"RUNTIME_LANGUAGE_COUNT":   RuntimeLanguageRUNTIME_LANGUAGE_COUNT,
}

func (v RuntimeLanguage) String() string {
	if s, ok := EnumNamesRuntimeLanguage[v]; ok {
		return s
	}
	return "RuntimeLanguage(" + strconv.FormatInt(int64(v), 10) + ")"
}
