// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package wls

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

// / Represents a String evaluator
// / Each evaluator has an ID, a comparison type and a value to compare against.
type StrEvaluator struct {
	_tab flatbuffers.Table
}

func GetRootAsStrEvaluator(buf []byte, offset flatbuffers.UOffsetT) *StrEvaluator {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &StrEvaluator{}
	x.Init(buf, n+offset)
	return x
}

func FinishStrEvaluatorBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsStrEvaluator(buf []byte, offset flatbuffers.UOffsetT) *StrEvaluator {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &StrEvaluator{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedStrEvaluatorBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *StrEvaluator) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *StrEvaluator) Table() flatbuffers.Table {
	return rcv._tab
}

// / The ID is a unique identifier for the evaluator.
func (rcv *StrEvaluator) Id() StringEvaluators {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return StringEvaluators(rcv._tab.GetInt8(o + rcv._tab.Pos))
	}
	return 0
}

// / The ID is a unique identifier for the evaluator.
func (rcv *StrEvaluator) MutateId(n StringEvaluators) bool {
	return rcv._tab.MutateInt8Slot(4, int8(n))
}

// / The comparison type is used to determine how to compare the value against the evaluator's value.
func (rcv *StrEvaluator) Cmp() CmpTypeSTR {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return CmpTypeSTR(rcv._tab.GetInt8(o + rcv._tab.Pos))
	}
	return 0
}

// / The comparison type is used to determine how to compare the value against the evaluator's value.
func (rcv *StrEvaluator) MutateCmp(n CmpTypeSTR) bool {
	return rcv._tab.MutateInt8Slot(6, int8(n))
}

// / The value is the value to compare against.
func (rcv *StrEvaluator) Value() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

// / The value is the value to compare against.
func StrEvaluatorStart(builder *flatbuffers.Builder) {
	builder.StartObject(3)
}
func StrEvaluatorAddId(builder *flatbuffers.Builder, id StringEvaluators) {
	builder.PrependInt8Slot(0, int8(id), 0)
}
func StrEvaluatorAddCmp(builder *flatbuffers.Builder, cmp CmpTypeSTR) {
	builder.PrependInt8Slot(1, int8(cmp), 0)
}
func StrEvaluatorAddValue(builder *flatbuffers.Builder, value flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(2, flatbuffers.UOffsetT(value), 0)
}
func StrEvaluatorEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
