// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package wls

import "strconv"

// / Each ID represents a String evaluator
// / Each evaluator ID should be UNIQUE!
// / IMPORTANT! When adding a new evaluator make sure you add it as the last one (just before the _COUNT entry)
type StringEvaluators int8

const (
	/// An enum representing the type of action to take.
	StringEvaluatorsSTRING_EVAL_UNKNOWN   StringEvaluators = 0
	StringEvaluatorsCOMPONENT             StringEvaluators = 1
	StringEvaluatorsPROCESS_EXE           StringEvaluators = 2
	StringEvaluatorsPROCESS_EXE_FULL_PATH StringEvaluators = 3
	StringEvaluatorsPROCESS_BASEDIR_PATH  StringEvaluators = 4
	StringEvaluatorsPROCESS_ARGV          StringEvaluators = 5
	StringEvaluatorsPROCESS_CWD           StringEvaluators = 6
	StringEvaluatorsRUNTIME_LANGUAGE      StringEvaluators = 7
	/// [python, node, .NET] the [.py/shebang, .js, .dll] file,
	StringEvaluatorsRUNTIME_ENTRY_POINT_FILE StringEvaluators = 8
	/// Used to evaluate the jar file passed to the JVM
	StringEvaluatorsRUNTIME_ENTRY_POINT_JAR StringEvaluators = 9
	/// Used to evaluate the class passed to the JVM
	StringEvaluatorsRUNTIME_ENTRY_POINT_CLASS StringEvaluators = 10
	/// Used to evaluate the class passed to the JVM
	StringEvaluatorsRUNTIME_ENTRY_POINT_PACKAGE StringEvaluators = 11
	StringEvaluatorsRUNTIME_ENTRY_POINT_MODULE  StringEvaluators = 12
	/// Used to evalute the source file passed to the JVM
	StringEvaluatorsRUNTIME_ENTRY_POINT_SOURCE StringEvaluators = 13
	/// Used to evaluate different Doptions passed to the JVM
	StringEvaluatorsRUNTIME_DOPTION StringEvaluators = 14
	/// Used to evaluate the runtime version
	/// Remember current implementation will only support string comparisons!
	/// For a numeric comparison look at the NumericEvaluators!
	StringEvaluatorsRUNTIME_VERSION StringEvaluators = 15
	/// Used to evaluate the flavors (glibc, musl, etc.)
	StringEvaluatorsLIBC_FLAVOR StringEvaluators = 16
	/// Used to evaluate the libc version
	/// Remember current implementation will only support string comparisons!
	/// For a numeric comparison look at the NumericEvaluators!
	StringEvaluatorsLIBC_VERSION StringEvaluators = 17
	/// Used to evaluate the architecture (x86_64, amd64, aarch64, etc.)
	StringEvaluatorsMACHINE_ARCHITECTURE StringEvaluators = 18
	/// Used to evaluate the hostname
	/// NOTE: the correctness of the hotname really depends heavily on the component implementing this evaluator!
	StringEvaluatorsHOST_NAME StringEvaluators = 19
	/// Used to evaluate the IP
	/// NOTE: the correctness of the hotname really depends heavily on the component implementing this evaluator!
	StringEvaluatorsHOST_IP            StringEvaluators = 20
	StringEvaluatorsOS                 StringEvaluators = 21
	StringEvaluatorsOS_DISTRO          StringEvaluators = 22
	StringEvaluatorsOS_DISTRO_VERSION  StringEvaluators = 23
	StringEvaluatorsOS_DISTRO_CODENAME StringEvaluators = 24
	StringEvaluatorsOS_KERNEL_VERSION  StringEvaluators = 25
	StringEvaluatorsOS_KERNEL_NAME     StringEvaluators = 26
	StringEvaluatorsOS_USER            StringEvaluators = 27
	StringEvaluatorsOS_USER_GROUP      StringEvaluators = 28
	StringEvaluatorsCONTAINER_IMAGE    StringEvaluators = 29
	StringEvaluatorsCONTAINER_ID       StringEvaluators = 30
	/// When you want to pass a true, false or abstain value to an
	/// action without evaluating anything, these can be used
	StringEvaluatorsALWAYS_TRUE          StringEvaluators = 31
	StringEvaluatorsALWAYS_FALSE         StringEvaluators = 32
	StringEvaluatorsALWAYS_ABSTAIN       StringEvaluators = 33
	StringEvaluatorsIIS_APPLICATION_POOL StringEvaluators = 34
	StringEvaluatorsPROCESS_ARGV_0       StringEvaluators = 35
	StringEvaluatorsPROCESS_ARGV_1       StringEvaluators = 36
	StringEvaluatorsPROCESS_ARGV_2       StringEvaluators = 37
	StringEvaluatorsPROCESS_ARGV_3       StringEvaluators = 38
	StringEvaluatorsPROCESS_ARGV_4       StringEvaluators = 39
	StringEvaluatorsPROCESS_ARGV_5       StringEvaluators = 40
	StringEvaluatorsPROCESS_ARGV_N       StringEvaluators = 41
	StringEvaluatorsPROCESS_ARGV_N_2     StringEvaluators = 42
	StringEvaluatorsPROCESS_ARGV_N_3     StringEvaluators = 43
	StringEvaluatorsPROCESS_ARGV_N_4     StringEvaluators = 44
	StringEvaluatorsPROCESS_ARGV_N_5     StringEvaluators = 45
	StringEvaluatorsPROCESS_ARGV_N_6     StringEvaluators = 46
	StringEvaluatorsPROCESS_ENVAR        StringEvaluators = 47
	/// The tag portion of the container image reference (e.g. "latest", "v2.1")
	StringEvaluatorsCONTAINER_IMAGE_TAG StringEvaluators = 48
	/// The OCI image digest, including the algorithm prefix (e.g. "sha256:abc123...")
	StringEvaluatorsCONTAINER_IMAGE_DIGEST StringEvaluators = 49
	/// The human-readable container name assigned by the container runtime
	StringEvaluatorsCONTAINER_NAME StringEvaluators = 50
	/// A container label as "KEY=VALUE", with CMP_WILDCARD can check wildcards too
	StringEvaluatorsCONTAINER_LABEL StringEvaluators = 51
	/// Kubernetes Single Step Instrumentation targeting evaluators.
	/// The name of the Kubernetes namespace the workload belongs to.
	StringEvaluatorsNAMESPACE_NAME StringEvaluators = 52
	/// A Kubernetes namespace label as "KEY=VALUE"; with CMP_WILDCARD can check
	/// wildcards too, and "KEY=" with CMP_PREFIX expresses an existence check.
	StringEvaluatorsNAMESPACE_LABEL StringEvaluators = 53
	/// A Kubernetes pod label as "KEY=VALUE"; same "KEY=VALUE" convention as NAMESPACE_LABEL.
	StringEvaluatorsPOD_LABEL StringEvaluators = 54
	/// A Kubernetes pod annotation as "KEY=VALUE"; same convention as POD_LABEL.
	StringEvaluatorsPOD_ANNOTATION StringEvaluators = 55
	/// Represents the count of String evaluators.
	/// This is used to ensure that the enum is always in sync with the number of evaluators.
	/// IMPORTANT! When adding a new evaluator make sure you add it BEFORE this entry.
	StringEvaluatorsSTR_EVAL_COUNT StringEvaluators = 56
)

var EnumNamesStringEvaluators = map[StringEvaluators]string{
	StringEvaluatorsSTRING_EVAL_UNKNOWN:         "STRING_EVAL_UNKNOWN",
	StringEvaluatorsCOMPONENT:                   "COMPONENT",
	StringEvaluatorsPROCESS_EXE:                 "PROCESS_EXE",
	StringEvaluatorsPROCESS_EXE_FULL_PATH:       "PROCESS_EXE_FULL_PATH",
	StringEvaluatorsPROCESS_BASEDIR_PATH:        "PROCESS_BASEDIR_PATH",
	StringEvaluatorsPROCESS_ARGV:                "PROCESS_ARGV",
	StringEvaluatorsPROCESS_CWD:                 "PROCESS_CWD",
	StringEvaluatorsRUNTIME_LANGUAGE:            "RUNTIME_LANGUAGE",
	StringEvaluatorsRUNTIME_ENTRY_POINT_FILE:    "RUNTIME_ENTRY_POINT_FILE",
	StringEvaluatorsRUNTIME_ENTRY_POINT_JAR:     "RUNTIME_ENTRY_POINT_JAR",
	StringEvaluatorsRUNTIME_ENTRY_POINT_CLASS:   "RUNTIME_ENTRY_POINT_CLASS",
	StringEvaluatorsRUNTIME_ENTRY_POINT_PACKAGE: "RUNTIME_ENTRY_POINT_PACKAGE",
	StringEvaluatorsRUNTIME_ENTRY_POINT_MODULE:  "RUNTIME_ENTRY_POINT_MODULE",
	StringEvaluatorsRUNTIME_ENTRY_POINT_SOURCE:  "RUNTIME_ENTRY_POINT_SOURCE",
	StringEvaluatorsRUNTIME_DOPTION:             "RUNTIME_DOPTION",
	StringEvaluatorsRUNTIME_VERSION:             "RUNTIME_VERSION",
	StringEvaluatorsLIBC_FLAVOR:                 "LIBC_FLAVOR",
	StringEvaluatorsLIBC_VERSION:                "LIBC_VERSION",
	StringEvaluatorsMACHINE_ARCHITECTURE:        "MACHINE_ARCHITECTURE",
	StringEvaluatorsHOST_NAME:                   "HOST_NAME",
	StringEvaluatorsHOST_IP:                     "HOST_IP",
	StringEvaluatorsOS:                          "OS",
	StringEvaluatorsOS_DISTRO:                   "OS_DISTRO",
	StringEvaluatorsOS_DISTRO_VERSION:           "OS_DISTRO_VERSION",
	StringEvaluatorsOS_DISTRO_CODENAME:          "OS_DISTRO_CODENAME",
	StringEvaluatorsOS_KERNEL_VERSION:           "OS_KERNEL_VERSION",
	StringEvaluatorsOS_KERNEL_NAME:              "OS_KERNEL_NAME",
	StringEvaluatorsOS_USER:                     "OS_USER",
	StringEvaluatorsOS_USER_GROUP:               "OS_USER_GROUP",
	StringEvaluatorsCONTAINER_IMAGE:             "CONTAINER_IMAGE",
	StringEvaluatorsCONTAINER_ID:                "CONTAINER_ID",
	StringEvaluatorsALWAYS_TRUE:                 "ALWAYS_TRUE",
	StringEvaluatorsALWAYS_FALSE:                "ALWAYS_FALSE",
	StringEvaluatorsALWAYS_ABSTAIN:              "ALWAYS_ABSTAIN",
	StringEvaluatorsIIS_APPLICATION_POOL:        "IIS_APPLICATION_POOL",
	StringEvaluatorsPROCESS_ARGV_0:              "PROCESS_ARGV_0",
	StringEvaluatorsPROCESS_ARGV_1:              "PROCESS_ARGV_1",
	StringEvaluatorsPROCESS_ARGV_2:              "PROCESS_ARGV_2",
	StringEvaluatorsPROCESS_ARGV_3:              "PROCESS_ARGV_3",
	StringEvaluatorsPROCESS_ARGV_4:              "PROCESS_ARGV_4",
	StringEvaluatorsPROCESS_ARGV_5:              "PROCESS_ARGV_5",
	StringEvaluatorsPROCESS_ARGV_N:              "PROCESS_ARGV_N",
	StringEvaluatorsPROCESS_ARGV_N_2:            "PROCESS_ARGV_N_2",
	StringEvaluatorsPROCESS_ARGV_N_3:            "PROCESS_ARGV_N_3",
	StringEvaluatorsPROCESS_ARGV_N_4:            "PROCESS_ARGV_N_4",
	StringEvaluatorsPROCESS_ARGV_N_5:            "PROCESS_ARGV_N_5",
	StringEvaluatorsPROCESS_ARGV_N_6:            "PROCESS_ARGV_N_6",
	StringEvaluatorsPROCESS_ENVAR:               "PROCESS_ENVAR",
	StringEvaluatorsCONTAINER_IMAGE_TAG:         "CONTAINER_IMAGE_TAG",
	StringEvaluatorsCONTAINER_IMAGE_DIGEST:      "CONTAINER_IMAGE_DIGEST",
	StringEvaluatorsCONTAINER_NAME:              "CONTAINER_NAME",
	StringEvaluatorsCONTAINER_LABEL:             "CONTAINER_LABEL",
	StringEvaluatorsNAMESPACE_NAME:              "NAMESPACE_NAME",
	StringEvaluatorsNAMESPACE_LABEL:             "NAMESPACE_LABEL",
	StringEvaluatorsPOD_LABEL:                   "POD_LABEL",
	StringEvaluatorsPOD_ANNOTATION:              "POD_ANNOTATION",
	StringEvaluatorsSTR_EVAL_COUNT:              "STR_EVAL_COUNT",
}

var EnumValuesStringEvaluators = map[string]StringEvaluators{
	"STRING_EVAL_UNKNOWN":         StringEvaluatorsSTRING_EVAL_UNKNOWN,
	"COMPONENT":                   StringEvaluatorsCOMPONENT,
	"PROCESS_EXE":                 StringEvaluatorsPROCESS_EXE,
	"PROCESS_EXE_FULL_PATH":       StringEvaluatorsPROCESS_EXE_FULL_PATH,
	"PROCESS_BASEDIR_PATH":        StringEvaluatorsPROCESS_BASEDIR_PATH,
	"PROCESS_ARGV":                StringEvaluatorsPROCESS_ARGV,
	"PROCESS_CWD":                 StringEvaluatorsPROCESS_CWD,
	"RUNTIME_LANGUAGE":            StringEvaluatorsRUNTIME_LANGUAGE,
	"RUNTIME_ENTRY_POINT_FILE":    StringEvaluatorsRUNTIME_ENTRY_POINT_FILE,
	"RUNTIME_ENTRY_POINT_JAR":     StringEvaluatorsRUNTIME_ENTRY_POINT_JAR,
	"RUNTIME_ENTRY_POINT_CLASS":   StringEvaluatorsRUNTIME_ENTRY_POINT_CLASS,
	"RUNTIME_ENTRY_POINT_PACKAGE": StringEvaluatorsRUNTIME_ENTRY_POINT_PACKAGE,
	"RUNTIME_ENTRY_POINT_MODULE":  StringEvaluatorsRUNTIME_ENTRY_POINT_MODULE,
	"RUNTIME_ENTRY_POINT_SOURCE":  StringEvaluatorsRUNTIME_ENTRY_POINT_SOURCE,
	"RUNTIME_DOPTION":             StringEvaluatorsRUNTIME_DOPTION,
	"RUNTIME_VERSION":             StringEvaluatorsRUNTIME_VERSION,
	"LIBC_FLAVOR":                 StringEvaluatorsLIBC_FLAVOR,
	"LIBC_VERSION":                StringEvaluatorsLIBC_VERSION,
	"MACHINE_ARCHITECTURE":        StringEvaluatorsMACHINE_ARCHITECTURE,
	"HOST_NAME":                   StringEvaluatorsHOST_NAME,
	"HOST_IP":                     StringEvaluatorsHOST_IP,
	"OS":                          StringEvaluatorsOS,
	"OS_DISTRO":                   StringEvaluatorsOS_DISTRO,
	"OS_DISTRO_VERSION":           StringEvaluatorsOS_DISTRO_VERSION,
	"OS_DISTRO_CODENAME":          StringEvaluatorsOS_DISTRO_CODENAME,
	"OS_KERNEL_VERSION":           StringEvaluatorsOS_KERNEL_VERSION,
	"OS_KERNEL_NAME":              StringEvaluatorsOS_KERNEL_NAME,
	"OS_USER":                     StringEvaluatorsOS_USER,
	"OS_USER_GROUP":               StringEvaluatorsOS_USER_GROUP,
	"CONTAINER_IMAGE":             StringEvaluatorsCONTAINER_IMAGE,
	"CONTAINER_ID":                StringEvaluatorsCONTAINER_ID,
	"ALWAYS_TRUE":                 StringEvaluatorsALWAYS_TRUE,
	"ALWAYS_FALSE":                StringEvaluatorsALWAYS_FALSE,
	"ALWAYS_ABSTAIN":              StringEvaluatorsALWAYS_ABSTAIN,
	"IIS_APPLICATION_POOL":        StringEvaluatorsIIS_APPLICATION_POOL,
	"PROCESS_ARGV_0":              StringEvaluatorsPROCESS_ARGV_0,
	"PROCESS_ARGV_1":              StringEvaluatorsPROCESS_ARGV_1,
	"PROCESS_ARGV_2":              StringEvaluatorsPROCESS_ARGV_2,
	"PROCESS_ARGV_3":              StringEvaluatorsPROCESS_ARGV_3,
	"PROCESS_ARGV_4":              StringEvaluatorsPROCESS_ARGV_4,
	"PROCESS_ARGV_5":              StringEvaluatorsPROCESS_ARGV_5,
	"PROCESS_ARGV_N":              StringEvaluatorsPROCESS_ARGV_N,
	"PROCESS_ARGV_N_2":            StringEvaluatorsPROCESS_ARGV_N_2,
	"PROCESS_ARGV_N_3":            StringEvaluatorsPROCESS_ARGV_N_3,
	"PROCESS_ARGV_N_4":            StringEvaluatorsPROCESS_ARGV_N_4,
	"PROCESS_ARGV_N_5":            StringEvaluatorsPROCESS_ARGV_N_5,
	"PROCESS_ARGV_N_6":            StringEvaluatorsPROCESS_ARGV_N_6,
	"PROCESS_ENVAR":               StringEvaluatorsPROCESS_ENVAR,
	"CONTAINER_IMAGE_TAG":         StringEvaluatorsCONTAINER_IMAGE_TAG,
	"CONTAINER_IMAGE_DIGEST":      StringEvaluatorsCONTAINER_IMAGE_DIGEST,
	"CONTAINER_NAME":              StringEvaluatorsCONTAINER_NAME,
	"CONTAINER_LABEL":             StringEvaluatorsCONTAINER_LABEL,
	"NAMESPACE_NAME":              StringEvaluatorsNAMESPACE_NAME,
	"NAMESPACE_LABEL":             StringEvaluatorsNAMESPACE_LABEL,
	"POD_LABEL":                   StringEvaluatorsPOD_LABEL,
	"POD_ANNOTATION":              StringEvaluatorsPOD_ANNOTATION,
	"STR_EVAL_COUNT":              StringEvaluatorsSTR_EVAL_COUNT,
}

func (v StringEvaluators) String() string {
	if s, ok := EnumNamesStringEvaluators[v]; ok {
		return s
	}
	return "StringEvaluators(" + strconv.FormatInt(int64(v), 10) + ")"
}
