// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package wls

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

/// Represents a String evaluator that can accept multiple values.
/// Represents an unsigned Numeric evaluator
/// This evaluator is used for unsigned numeric comparisons.
type UNumEvaluator struct {
	_tab flatbuffers.Table
}

func GetRootAsUNumEvaluator(buf []byte, offset flatbuffers.UOffsetT) *UNumEvaluator {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &UNumEvaluator{}
	x.Init(buf, n+offset)
	return x
}

func FinishUNumEvaluatorBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsUNumEvaluator(buf []byte, offset flatbuffers.UOffsetT) *UNumEvaluator {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &UNumEvaluator{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedUNumEvaluatorBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *UNumEvaluator) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *UNumEvaluator) Table() flatbuffers.Table {
	return rcv._tab
}

/// Each evaluator has an ID, a comparison type and a value to compare against.
func (rcv *UNumEvaluator) Id() NumericEvaluators {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return NumericEvaluators(rcv._tab.GetInt8(o + rcv._tab.Pos))
	}
	return 0
}

/// Each evaluator has an ID, a comparison type and a value to compare against.
func (rcv *UNumEvaluator) MutateId(n NumericEvaluators) bool {
	return rcv._tab.MutateInt8Slot(4, int8(n))
}

/// The comparison type is used to determine how to compare the value against the evaluator's value.
func (rcv *UNumEvaluator) Cmp() CmpTypeNUM {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return CmpTypeNUM(rcv._tab.GetInt8(o + rcv._tab.Pos))
	}
	return 0
}

/// The comparison type is used to determine how to compare the value against the evaluator's value.
func (rcv *UNumEvaluator) MutateCmp(n CmpTypeNUM) bool {
	return rcv._tab.MutateInt8Slot(6, int8(n))
}

/// The value is an unsigned long.
func (rcv *UNumEvaluator) Value() uint64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		return rcv._tab.GetUint64(o + rcv._tab.Pos)
	}
	return 0
}

/// The value is an unsigned long.
func (rcv *UNumEvaluator) MutateValue(n uint64) bool {
	return rcv._tab.MutateUint64Slot(8, n)
}

func UNumEvaluatorStart(builder *flatbuffers.Builder) {
	builder.StartObject(3)
}
func UNumEvaluatorAddId(builder *flatbuffers.Builder, id NumericEvaluators) {
	builder.PrependInt8Slot(0, int8(id), 0)
}
func UNumEvaluatorAddCmp(builder *flatbuffers.Builder, cmp CmpTypeNUM) {
	builder.PrependInt8Slot(1, int8(cmp), 0)
}
func UNumEvaluatorAddValue(builder *flatbuffers.Builder, value uint64) {
	builder.PrependUint64Slot(2, value, 0)
}
func UNumEvaluatorEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
