#ifndef VALUE_SETS_READER_H
#define VALUE_SETS_READER_H

/* Generated by flatcc 0.6.2 FlatBuffers schema compiler for C by dvide.com */

#ifndef FLATBUFFERS_COMMON_READER_H
#include "flatbuffers_common_reader.h"
#endif
#include "flatcc/flatcc_flatbuffers.h"
#ifndef __alignas_is_defined
#include <stdalign.h>
#endif
#include "flatcc/flatcc_prologue.h"
#ifndef flatbuffers_identifier
#define flatbuffers_identifier 0
#endif
#ifndef flatbuffers_extension
#define flatbuffers_extension "bin"
#endif



/**  Canonical set of runtime languages recognized by the policy engine.
 *  The string representation uses lowercase (e.g. "jvm", "python").
 *  IMPORTANT! When adding a new value make sure you add it BEFORE the _COUNT entry. */
typedef int8_t dd_wls_RuntimeLanguage_enum_t;
__flatbuffers_define_integer_type(dd_wls_RuntimeLanguage, dd_wls_RuntimeLanguage_enum_t, 8)
#define dd_wls_RuntimeLanguage_RUNTIME_LANGUAGE_UNKNOWN ((dd_wls_RuntimeLanguage_enum_t)INT8_C(0))
#define dd_wls_RuntimeLanguage_JVM ((dd_wls_RuntimeLanguage_enum_t)INT8_C(1))
#define dd_wls_RuntimeLanguage_PYTHON ((dd_wls_RuntimeLanguage_enum_t)INT8_C(2))
#define dd_wls_RuntimeLanguage_RUBY ((dd_wls_RuntimeLanguage_enum_t)INT8_C(3))
#define dd_wls_RuntimeLanguage_DOTNET ((dd_wls_RuntimeLanguage_enum_t)INT8_C(4))
#define dd_wls_RuntimeLanguage_NODEJS ((dd_wls_RuntimeLanguage_enum_t)INT8_C(5))
#define dd_wls_RuntimeLanguage_PHP ((dd_wls_RuntimeLanguage_enum_t)INT8_C(6))
#define dd_wls_RuntimeLanguage_RUNTIME_LANGUAGE_COUNT ((dd_wls_RuntimeLanguage_enum_t)INT8_C(7))

static inline const char *dd_wls_RuntimeLanguage_name(dd_wls_RuntimeLanguage_enum_t value)
{
    switch (value) {
    case dd_wls_RuntimeLanguage_RUNTIME_LANGUAGE_UNKNOWN: return "RUNTIME_LANGUAGE_UNKNOWN";
    case dd_wls_RuntimeLanguage_JVM: return "JVM";
    case dd_wls_RuntimeLanguage_PYTHON: return "PYTHON";
    case dd_wls_RuntimeLanguage_RUBY: return "RUBY";
    case dd_wls_RuntimeLanguage_DOTNET: return "DOTNET";
    case dd_wls_RuntimeLanguage_NODEJS: return "NODEJS";
    case dd_wls_RuntimeLanguage_PHP: return "PHP";
    case dd_wls_RuntimeLanguage_RUNTIME_LANGUAGE_COUNT: return "RUNTIME_LANGUAGE_COUNT";
    default: return "";
    }
}

static inline int dd_wls_RuntimeLanguage_is_known_value(dd_wls_RuntimeLanguage_enum_t value)
{
    switch (value) {
    case dd_wls_RuntimeLanguage_RUNTIME_LANGUAGE_UNKNOWN: return 1;
    case dd_wls_RuntimeLanguage_JVM: return 1;
    case dd_wls_RuntimeLanguage_PYTHON: return 1;
    case dd_wls_RuntimeLanguage_RUBY: return 1;
    case dd_wls_RuntimeLanguage_DOTNET: return 1;
    case dd_wls_RuntimeLanguage_NODEJS: return 1;
    case dd_wls_RuntimeLanguage_PHP: return 1;
    case dd_wls_RuntimeLanguage_RUNTIME_LANGUAGE_COUNT: return 1;
    default: return 0;
    }
}

/**  Canonical set of operating systems recognized by the policy engine.
 *  The string representation uses lowercase (e.g. "linux", "windows").
 *  IMPORTANT! When adding a new value make sure you add it BEFORE the _COUNT entry. */
typedef int8_t dd_wls_OperatingSystem_enum_t;
__flatbuffers_define_integer_type(dd_wls_OperatingSystem, dd_wls_OperatingSystem_enum_t, 8)
#define dd_wls_OperatingSystem_OS_UNKNOWN ((dd_wls_OperatingSystem_enum_t)INT8_C(0))
#define dd_wls_OperatingSystem_LINUX ((dd_wls_OperatingSystem_enum_t)INT8_C(1))
#define dd_wls_OperatingSystem_WINDOWS ((dd_wls_OperatingSystem_enum_t)INT8_C(2))
#define dd_wls_OperatingSystem_MACOS ((dd_wls_OperatingSystem_enum_t)INT8_C(3))
#define dd_wls_OperatingSystem_OS_COUNT ((dd_wls_OperatingSystem_enum_t)INT8_C(4))

static inline const char *dd_wls_OperatingSystem_name(dd_wls_OperatingSystem_enum_t value)
{
    switch (value) {
    case dd_wls_OperatingSystem_OS_UNKNOWN: return "OS_UNKNOWN";
    case dd_wls_OperatingSystem_LINUX: return "LINUX";
    case dd_wls_OperatingSystem_WINDOWS: return "WINDOWS";
    case dd_wls_OperatingSystem_MACOS: return "MACOS";
    case dd_wls_OperatingSystem_OS_COUNT: return "OS_COUNT";
    default: return "";
    }
}

static inline int dd_wls_OperatingSystem_is_known_value(dd_wls_OperatingSystem_enum_t value)
{
    switch (value) {
    case dd_wls_OperatingSystem_OS_UNKNOWN: return 1;
    case dd_wls_OperatingSystem_LINUX: return 1;
    case dd_wls_OperatingSystem_WINDOWS: return 1;
    case dd_wls_OperatingSystem_MACOS: return 1;
    case dd_wls_OperatingSystem_OS_COUNT: return 1;
    default: return 0;
    }
}

/**  Canonical set of machine architectures recognized by the policy engine.
 *  The string representation uses the kernel-reported format (e.g. "aarch64", "x86_64", "arm").
 *  IMPORTANT! When adding a new value make sure you add it BEFORE the _COUNT entry. */
typedef int8_t dd_wls_MachineArchitecture_enum_t;
__flatbuffers_define_integer_type(dd_wls_MachineArchitecture, dd_wls_MachineArchitecture_enum_t, 8)
#define dd_wls_MachineArchitecture_ARCH_UNKNOWN ((dd_wls_MachineArchitecture_enum_t)INT8_C(0))
#define dd_wls_MachineArchitecture_AARCH64 ((dd_wls_MachineArchitecture_enum_t)INT8_C(1))
#define dd_wls_MachineArchitecture_X86_64 ((dd_wls_MachineArchitecture_enum_t)INT8_C(2))
#define dd_wls_MachineArchitecture_ARM ((dd_wls_MachineArchitecture_enum_t)INT8_C(3))
#define dd_wls_MachineArchitecture_MACHINE_ARCHITECTURE_COUNT ((dd_wls_MachineArchitecture_enum_t)INT8_C(4))

static inline const char *dd_wls_MachineArchitecture_name(dd_wls_MachineArchitecture_enum_t value)
{
    switch (value) {
    case dd_wls_MachineArchitecture_ARCH_UNKNOWN: return "ARCH_UNKNOWN";
    case dd_wls_MachineArchitecture_AARCH64: return "AARCH64";
    case dd_wls_MachineArchitecture_X86_64: return "X86_64";
    case dd_wls_MachineArchitecture_ARM: return "ARM";
    case dd_wls_MachineArchitecture_MACHINE_ARCHITECTURE_COUNT: return "MACHINE_ARCHITECTURE_COUNT";
    default: return "";
    }
}

static inline int dd_wls_MachineArchitecture_is_known_value(dd_wls_MachineArchitecture_enum_t value)
{
    switch (value) {
    case dd_wls_MachineArchitecture_ARCH_UNKNOWN: return 1;
    case dd_wls_MachineArchitecture_AARCH64: return 1;
    case dd_wls_MachineArchitecture_X86_64: return 1;
    case dd_wls_MachineArchitecture_ARM: return 1;
    case dd_wls_MachineArchitecture_MACHINE_ARCHITECTURE_COUNT: return 1;
    default: return 0;
    }
}




#include "flatcc/flatcc_epilogue.h"
#endif /* VALUE_SETS_READER_H */
