#ifndef VALUE_SETS_BUILDER_H
#define VALUE_SETS_BUILDER_H

/* Generated by flatcc 0.6.2 FlatBuffers schema compiler for C by dvide.com */

#ifndef VALUE_SETS_READER_H
#include "value_sets_reader.h"
#endif
#ifndef FLATBUFFERS_COMMON_BUILDER_H
#include "flatbuffers_common_builder.h"
#endif
#include "flatcc/flatcc_prologue.h"
#ifndef flatbuffers_identifier
#define flatbuffers_identifier 0
#endif
#ifndef flatbuffers_extension
#define flatbuffers_extension "bin"
#endif

#define __dd_wls_RuntimeLanguage_formal_args , dd_wls_RuntimeLanguage_enum_t v0
#define __dd_wls_RuntimeLanguage_call_args , v0
__flatbuffers_build_scalar(flatbuffers_, dd_wls_RuntimeLanguage, dd_wls_RuntimeLanguage_enum_t)
#define __dd_wls_OperatingSystem_formal_args , dd_wls_OperatingSystem_enum_t v0
#define __dd_wls_OperatingSystem_call_args , v0
__flatbuffers_build_scalar(flatbuffers_, dd_wls_OperatingSystem, dd_wls_OperatingSystem_enum_t)

#include "flatcc/flatcc_epilogue.h"
#endif /* VALUE_SETS_BUILDER_H */
