#ifndef VALUE_SETS_VERIFIER_H
#define VALUE_SETS_VERIFIER_H

/* Generated by flatcc 0.6.2 FlatBuffers schema compiler for C by dvide.com */

#ifndef VALUE_SETS_READER_H
#include "value_sets_reader.h"
#endif
#include "flatcc/flatcc_verifier.h"
#include "flatcc/flatcc_prologue.h"


#include "flatcc/flatcc_epilogue.h"
#endif /* VALUE_SETS_VERIFIER_H */
