// Garbage generated by OpenAI but good enough for a POC.
package parser

import (
	"encoding/json"
	"fmt"
	"strings"
)

// AST node definitions
type Node any

type EmptyNode struct{}

type Comparator int

const (
	Exact Comparator = iota
	Prefix
	Suffix
	Contains
)

func (comp Comparator) String() string {
	switch comp {
	case Exact:
		return "EXACT"
	case Prefix:
		return "PREFIX"
	case Suffix:
		return "SUFFIX"
	case Contains:
		return "CONTAINS"
	}
	panic("unexpected comparator")
}

func (c Comparator) MarshalText() ([]byte, error) {
	return []byte(c.String()), nil
}

type TermNode struct {
	Field      string     `json:"Field"`
	Value      string     `json:"Value"`
	Comparator Comparator `json:"Comparator"`
}

type BooleanOperator int

const (
	Or BooleanOperator = iota
	And
)

func (b BooleanOperator) String() string {
	switch b {
	case Or:
		return "OR"
	case And:
		return "AND"
	}
	panic("unexpected boolean operator")
}

type BooleanNode struct {
	Left  Node            `json:"Left"`
	Right Node            `json:"Right"`
	Kind  BooleanOperator `json:"Comparator"`
}

// Parser
type parser struct {
	lexer  *lexer
	tokens chan Token
}

func parser_new(input string) *parser {
	lexer, tokens := lex(input)
	return &parser{lexer: lexer, tokens: tokens}
}

func (p *parser) nextToken() Token {
	token := <-p.tokens
	return token
}

func (p *parser) error(err string, token Token) error {
	return &parserError{message: err, input: p.lexer.input, errorPos: token.Start}
}

func (p *parser) parseTerm() (Node, error) {
	field := p.nextToken()
	if field.Type != tokenKey {
		return &EmptyNode{}, p.error("expected field name", field)
	}
	value := p.nextToken()
	if value.Type != tokenValue {
		return &EmptyNode{}, p.error("expected field value", value)
	}
	return &TermNode{Field: field.Value, Value: value.Value, Comparator: Exact}, nil
}

func (p *parser) parseFactor() (Node, error) {
	// tok := p.peek()
	// if tok.Type == TokenLParen {
	// 	p.consume()
	// 	node, err := p.parseExpr()
	// 	if err != nil {
	// 		return &EmptyNode{}, err
	// 	}
	// 	if p.peek().Type != TokenRParen {
	// 		return &EmptyNode{}, errors.New("expected closing )")
	// 	}
	// 	p.consume()
	// 	return node, nil
	// }
	return p.parseTerm()
}

func (p *parser) parseExpr() (Node, error) {
	node, err := p.parseFactor()
	if err != nil {
		return &EmptyNode{}, err
	}
	for {
		token := p.nextToken()
		if token.Type == tokenAnd {
			right, err := p.parseFactor()
			if err != nil {
				return &EmptyNode{}, err
			}
			node = &BooleanNode{Left: node, Right: right, Kind: And}
		} else if token.Type == tokenOr {
			right, err := p.parseFactor()
			if err != nil {
				return &EmptyNode{}, err
			}
			node = &BooleanNode{Left: node, Right: right, Kind: Or}
		} else if token.Type == tokenEOF {
			break
		} else {
			return &EmptyNode{}, p.error("unexpected token", token)
		}
	}
	return node, nil
}

func Parse(input string) (AST, error) {
	parser := parser_new(input)
	n, err := parser.parseExpr()
	return AST{Node: n}, err
}

func printAST(node Node, indent string) string {
	var sb strings.Builder

	switch n := node.(type) {
	case *TermNode:
		sb.WriteString(fmt.Sprintf("%s Term(key = \"%s\", value = \"%s\", comparator = \"%s\")\n", indent, n.Field, n.Value, n.Comparator))
	case *BooleanNode:
		leftIndent := indent
		if _, ok := n.Left.(*TermNode); ok {
			leftIndent += "  ├──"
		} else {
			leftIndent += "  │"
		}

		sb.WriteString(fmt.Sprintf("%s Predicate(kind = %s):\n", indent, n.Kind))
		sb.WriteString(printAST(n.Left, leftIndent))
		sb.WriteString(printAST(n.Right, indent+"  └──"))
	default:
		sb.WriteString(fmt.Sprintf("%sUnknown node\n", indent))
	}

	return sb.String()
}

type AST struct {
	Node Node
}

func (ast AST) String() string {
	return printAST(ast.Node, "")
}

func (ast AST) MarshalJSON() ([]byte, error) {
	return json.Marshal(ast.Node)
}

func (b BooleanOperator) MarshalText() ([]byte, error) {
	return []byte(b.String()), nil
}

func (b *BooleanNode) MarshalJSON() ([]byte, error) {
	type Alias BooleanNode
	return json.Marshal(map[string]*Alias{
		"BooleanNode": (*Alias)(b),
	})
}

type parserError struct {
	message  string
	input    string
	errorPos int
}

func (e *parserError) Error() string {
	var sb strings.Builder
	sb.WriteString(fmt.Sprintf("%s\n", e.input))

	// Create a line of spaces up to errorPos and place a caret
	if e.errorPos < 0 || e.errorPos > len(e.input) {
		underline := strings.Repeat("^", len(e.input))
		sb.WriteString(underline)
		sb.WriteString(e.message)
		return sb.String()
	}

	caretLine := strings.Repeat(" ", e.errorPos) + "^------- " + e.message
	sb.WriteString(caretLine)
	return sb.String()
}
