name: Development
on: [pull_request, workflow_dispatch]

env: 
  # Override the `DOCKER_IMAGE` variable in Makefile.docker  
  # This makes all Makefile targets use the specified Docker image instead of building a new one.
  DOCKER_IMAGE: datadog/docker-library:dd-policy-engine-a0f48dd
  BUILD_CONTAINER: false

jobs:
  checks:
    runs-on: ubuntu-22.04
    timeout-minutes: 5
    permissions:
      contents: read
      packages: read
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - run: make fmt-check

  build-linux:
    strategy:
      fail-fast: false
      matrix:
        toolchain: [gcc, clang]
        arch: [amd64, arm64]
        include:
          - arch: amd64
            runner: ubuntu-22.04
          - arch: arm64
            runner: ubuntu-22.04-arm
    needs: checks
    runs-on: ${{ matrix.runner }}
    timeout-minutes: 10
    environment:
      name: dev-env
    permissions:
      contents: read
      packages: read
    env:
      DD_ENV: ci
      DD_SERVICE: dd-policy-engine
      DD_CIVISIBILITY_AGENTLESS_ENABLED: true
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - name: Build
        run: make docker-run "make -C c test-build"
        env:
          DOCKER_ENVARS: "-e CMAKE_PRESET=${{ matrix.toolchain }}-ci"
      - name: Run Tests
        run: make docker-run "./c/build/c/src/test/dd-policy-engine.unit-tests --random-order --output test-report.xml"
        env:
          DOCKER_ENVARS: "-e LSAN_OPTIONS=suppressions=.lsan.supp"
      - name: Report test coverage
        uses: datadog/junit-upload-github-action@762867566348d59ac9bcf479ebb4ec040db8940a # v2.0.0
        with:
          api_key: ${{ secrets.DD_API_KEY_CI_VIS_APP }}
          files: c/build/test-report.xml
          # tags: test.source.file:test/*.cpp

  # Dedicated job for building dd-compile-policy
  build-dd-compile-policy:
    needs: checks
    strategy:
      fail-fast: false
      matrix:
        arch: [amd64, arm64]
        include:
          - arch: amd64
            runner: ubuntu-22.04
          - arch: arm64
            runner: ubuntu-22.04-arm
    runs-on: ${{ matrix.runner }}
    timeout-minutes: 10
    environment:
      name: dev-env
    permissions:
      contents: read
      packages: read
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - name: Build dd-compile-policy
        run: make build-dd-compile-policy
      - name: Export dd-compile-policy
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4.6.2
        with:
          name: dd-compile-policy-linux-${{ matrix.arch }}
          path: dd-compile-policy/bin/dd-compile-policy

  # TODO: add arch and vs versions
  build-windows:
    needs: checks
    runs-on: windows-2022
    timeout-minutes: 10
    defaults:
      run:
        shell: powershell
    environment:
      name: dev-env
    permissions:
      contents: read
      packages: read
    env:
      DD_ENV: ci
      DD_SERVICE: dd-policy-engine
      DD_API_KEY: ${{ secrets.DD_API_KEY_CI_VIS_APP }}
      DD_CIVISIBILITY_AGENTLESS_ENABLED: true
      CMAKE_POLICY_VERSION_MINIMUM: 3.5
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - name: Setup MSVC
        uses: ilammy/msvc-dev-cmd@0b201ec74fa43914dc39ae48a89fd1d8cb592756 # v1.13.0
        with:
          arch: x64
      - name: Install Dependency Manager (scoop)
        run: |
          Set-ExecutionPolicy -ExecutionPolicy RemoteSigned -Scope CurrentUser
          Invoke-RestMethod -Uri https://get.scoop.sh | Invoke-Expression
          Join-Path (Resolve-Path ~).Path "scoop\shims" >> $Env:GITHUB_PATH
      - name: Install Dependencies
        run: scoop install main/cmake@4.0.1
      - name: Build
        run: |
          cmake -B build --preset msvc-ci .
          cmake --build build -j
      - name: Run tests
        run: ctest --test-dir build --output-junit test-report.xml
        timeout-minutes: 2
      - name: Download datadog-ci
        run: Invoke-WebRequest -Uri "https://github.com/DataDog/datadog-ci/releases/latest/download/datadog-ci_win-x64" -OutFile "datadog-ci.exe"
      - name: Report test coverage
        run: ./datadog-ci.exe junit upload build/test-report.xml

  coverage:
    needs: build-linux
    runs-on: ubuntu-22.04-arm
    timeout-minutes: 10
    environment:
      name: dev-env
    permissions:
      contents: read
      packages: read
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - run: make docker-run "make -C c coverage"
      - name: Upload coverage reports to Datadog
        run: |
          curl -L --fail "https://github.com/DataDog/datadog-ci/releases/latest/download/datadog-ci_linux-arm64" --output "/tmp/datadog-ci"
          chmod +x /tmp/datadog-ci
          mv c/coverage/coverage.lcov c/coverage/lcov.info
          /tmp/datadog-ci coverage upload c/coverage/lcov.info
        env:
          DD_API_KEY: ${{ secrets.DD_API_KEY_CI_VIS_APP }}
