name: Release
on: [workflow_dispatch]

jobs:
  build-and-package-linux:
    runs-on: ubuntu-22.04
    timeout-minutes: 10
    container:
      image: datadog/docker-library:dd-policy-engine-35a0551
    environment:
      name: dev-env
    permissions:
      contents: read
      packages: read
    env:
      IN_DOCKER: "true"
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - name: Configure
        run: cmake -B build --preset clang-release .
      - name: Build
        run: cmake --build build --target dd-policy-engine.static-lib -j
      - name: Install
        run: cmake --install build --prefix=dist
      - name: Export library
        uses: actions/upload-artifact@v4
        with:
          name: libpolicies-linux
          path: dist

  # Dedicated job for building dd-compile-policy
  build-dd-compile-policy:
    strategy:
      fail-fast: false
      matrix:
        arch: [amd64, arm64]
        include:
          - arch: amd64
            runner: ubuntu-22.04
          - arch: arm64
            runner: ubuntu-22.04-arm
    runs-on: ${{ matrix.runner }}
    container:
      image: datadog/docker-library:dd-policy-engine-35a0551-${{ matrix.arch }}
    timeout-minutes: 10
    environment:
      name: dev-env
    permissions:
      contents: write
      packages: read
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - name: Build docker image  # TODO: use {{ matrix.docker-image }} once it's up to date
        run: make build-container
      - name: Build dd-compile-policy
        run: make build-dd-compile-policy
      - name: Create tarball for dd-compile-policy
        run: tar -czf dd-compile-policy-linux-${{ matrix.arch }}.tar.gz -C dd-compile-policy/bin dd-compile-policy
      - name: Upload release assets
        uses: softprops/action-gh-release@6cbd405e2c4e67a21c47fa9e383d020e4e28b836 # v2.3.3
        with:
          files: dd-compile-policy-linux-${{ matrix.arch }}.tar.gz
          draft: true

  build-and-package-windows:
    strategy:
      fail-fast: false
      matrix:
        arch: ["x64", "x86"]
    runs-on: windows-2022
    timeout-minutes: 10
    defaults:
      run:
        shell: powershell
    environment:
      name: dev-env
    permissions:
      contents: read
      packages: read
    env:
      CMAKE_POLICY_VERSION_MINIMUM: 3.5
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - name: Setup MSVC
        uses: ilammy/msvc-dev-cmd@0b201ec74fa43914dc39ae48a89fd1d8cb592756 # v1.13.0
        with:
          arch: ${{ matrix.arch }}
      - name: Install Dependency Manager (scoop)
        run: |
          Set-ExecutionPolicy -ExecutionPolicy RemoteSigned -Scope CurrentUser
          Invoke-RestMethod -Uri https://get.scoop.sh | Invoke-Expression
          Join-Path (Resolve-Path ~).Path "scoop\shims" >> $Env:GITHUB_PATH
      - name: Install Dependencies
        run: scoop install main/cmake@4.0.1
      - name: Build
        run: |
          cmake -B build --preset msvc-release .
          cmake --build build --target dd-policy-engine.static-lib -j
          cmake --install build --prefix=dist
      - name: Export library
        uses: actions/upload-artifact@v4
        with:
          name: libpolicies-win-${{ matrix.arch }}
          path: dist
