name: Release
on:
  workflow_dispatch:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+*'

env: 
  # Override the `DOCKER_IMAGE` variable in Makefile.docker  
  # This makes all Makefile targets use the specified Docker image instead of building a new one.
  DOCKER_IMAGE: datadog/docker-library:dd-policy-engine-88ce93f
  BUILD_CONTAINER: false

jobs:
  package-linux:
    strategy:
      fail-fast: true
      matrix:
        arch: [amd64, arm64]
        include:
          - arch: amd64
            runner: ubuntu-22.04
          - arch: arm64
            runner: ubuntu-22.04-arm
    runs-on: ${{ matrix.runner }}
    timeout-minutes: 10
    permissions:
      contents: read
      packages: read
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      - name: Configure
        run: make docker-run "cmake -B build --preset gcc-release ."
      - name: Build libpolicies
        run: |
          make docker-run "cmake --build build --target dd-policy-engine.static-lib -j"
          make docker-run "cmake --install build --prefix=libpolicies"
      - name: Package libpolicies
        run: tar -czf libpolicies-linux-${{ matrix.arch }}.tar.gz libpolicies
      - name: Build dd-requirements-converter
        run: make docker-run "make -C go build"
      - name: Package dd-requirements-converter
        run: tar -czf dd-requirements-converter-linux-${{ matrix.arch }}.tar.gz go/dd-requirements-converter
      - name: Export library
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: libpolicies-linux-${{ matrix.arch }}
          path: |
            libpolicies-linux-${{ matrix.arch }}.tar.gz
            dd-requirements-converter-linux-${{ matrix.arch }}.tar.gz

  package-dd-compile-policy-linux:
    strategy:
      fail-fast: true
      matrix:
        arch: [amd64, arm64]
        include:
          - arch: amd64
            runner: ubuntu-22.04
          - arch: arm64
            runner: ubuntu-22.04-arm
    runs-on: ${{ matrix.runner }}
    timeout-minutes: 10
    permissions:
      contents: read
      packages: read
    steps:
      - name: Checkout
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      - name: Build dd-compile-policy
        run: make build-dd-compile-policy
      - name: Package dd-compile-policy
        run: tar -czf dd-compile-policy-linux-${{ matrix.arch }}.tar.gz -C dd-compile-policy/bin dd-compile-policy
      - name: Upload test artifacts
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: dd-compile-policy-linux-${{ matrix.arch }}.tar.gz
          path: dd-compile-policy-linux-${{ matrix.arch }}.tar.gz

  package-dd-compile-policy-windows:
    strategy:
      fail-fast: false
      matrix:
        arch: [x64]
    runs-on: windows-2022
    timeout-minutes: 10
    defaults:
      run:
        shell: powershell
    permissions:
      contents: read
      packages: read
    steps:
      - name: Checkout
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      - name: Setup MSVC
        uses: ilammy/msvc-dev-cmd@0b201ec74fa43914dc39ae48a89fd1d8cb592756 # v1.13.0
        with:
          arch: ${{ matrix.arch }}
      - name: Install Dependency Manager (scoop)
        run: |
          Set-ExecutionPolicy -ExecutionPolicy RemoteSigned -Scope CurrentUser
          Invoke-RestMethod -Uri https://get.scoop.sh | Invoke-Expression
          Join-Path (Resolve-Path ~).Path "scoop\shims" >> $Env:GITHUB_PATH
      - name: Install Dependencies
        run: scoop install main/cmake@4.0.1 main/make@4.4.1
      - name: Build dd-compile-policy
        run: make -C dd-compile-policy build CMAKE_ARCH=${{ matrix.arch }}
      - name: Package dd-compile-policy
        run: Compress-Archive -Path ./dd-compile-policy/bin/dd-compile-policy.exe -DestinationPath dd-compile-policy-windows-${{ matrix.arch }}.zip
      - name: Upload dd-compile-policy
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: dd-compile-policy-windows-${{ matrix.arch }}.zip
          path: dd-compile-policy-windows-${{ matrix.arch }}.zip

  package-windows:
    strategy:
      fail-fast: false
      matrix:
        arch: ["x64", "x86"]
    runs-on: windows-2022
    timeout-minutes: 10
    defaults:
      run:
        shell: powershell
    permissions:
      contents: read
      packages: read
    env:
      CMAKE_POLICY_VERSION_MINIMUM: 3.5
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      - name: Setup MSVC
        uses: ilammy/msvc-dev-cmd@0b201ec74fa43914dc39ae48a89fd1d8cb592756 # v1.13.0
        with:
          arch: ${{ matrix.arch }}
      - name: Install Dependency Manager (scoop)
        run: |
          Set-ExecutionPolicy -ExecutionPolicy RemoteSigned -Scope CurrentUser
          Invoke-RestMethod -Uri https://get.scoop.sh | Invoke-Expression
          Join-Path (Resolve-Path ~).Path "scoop\shims" >> $Env:GITHUB_PATH
      - name: Install Dependencies
        run: scoop install main/cmake@4.0.1 go
      - name: Build
        run: |
          cmake -B build --preset msvc-release .
          cmake --build build --target dd-policy-engine.static-lib -j
          cmake --install build --prefix=libpolicies
      - name: Package libpolicies
        run: Compress-Archive -Path ./libpolicies -DestinationPath libpolicies-win-${{ matrix.arch }}.zip
      - name: Build Go commands
        run: |
          go build -o dd-requirements-converter.exe ./cmd/dd-requirements-converter
        working-directory: go
      - name: Package dd-requirements-converter
        run: Compress-Archive -Path ./go/dd-requirements-converter.exe -DestinationPath dd-requirements-converter-win-${{ matrix.arch }}.zip
      - name: Export library
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: libpolicies-win-${{ matrix.arch }}
          path: |
            libpolicies-win-${{ matrix.arch }}.zip
            dd-requirements-converter-win-${{ matrix.arch }}.zip

  generate-github-draft-release:
    if: github.event_name != 'workflow_dispatch'
    needs: [package-windows, package-linux, package-dd-compile-policy-linux, package-dd-compile-policy-windows]
    runs-on: ubuntu-22.04-arm
    environment:
      name: release
    permissions:
      contents: write
      packages: read
    steps:
      - name: Checkout
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      - uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c # v8.0.1
        with:
          path: artifacts
          merge-multiple: true
      - name: Create release
        run: gh release create ${{ github.ref_name }} --draft --generate-notes --verify-tag artifacts/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
